### ISSUE TITLE
conflict on simple.js

### ISSUE THREAD

**Issue by KT19** [UTokyo-SDP/ex-02-g19-40#8]
developをup-to-data->そのままdevelopでsimple.jsのgetおよびdelete(まだ未完成)を修正->push
した結果、simple.jsでconfrictが一部発生したようです。。。

**Comment by Mai1126** [comment]
コンフリクトが確認できませんでした…
テストを全部通したのをpushしました。

参考までに、無理やりpullする方法。
http://www-creators.com/archives/1097

**Comment by KT19** [comment]
俺の勘違いだったかな・・・？
テスト通ったならOKだし、ありがとう。
